DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (194, 194)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  MAX_EPOCH: 1000

TRAIN:
  PRINT_FREQ: 20

TRAINER:
  BASIC:
    OPT_TYPE: "spsa-gc"
    SP_AVG: 5
  BAR:
    METHOD: 'reprogramming'
    FRAME_SIZE: 224
    SMOOTH: 0.01
    SIMGA: 1.0
    LRS: [10.0,0.1]
    FOCAL_G: 2.0

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"