DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  MAX_EPOCH: 1000

TRAIN:
  PRINT_FREQ: 20

TRAINER:
  BPTVLM:
    TOKENS_L: 5
    TOKENS_V: 5
    INTRINSIC_DIM_L: 2000
    INTRINSIC_DIM_V: 2000
    SIGMA: 1
    POP_SIZE: 15

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"
